require_relative "./top-30-games/version"
require_relative "./top-30-games/cli"
require_relative "./top-30-games/scraper"
require_relative "./top-30-games/game"
require "nokogiri"
require "open-uri"
require "pry"
